In [33]:
import pandas as pd

In [35]:
data = {
    'Apples': [3, 2, 0, 1],
    'Oranges': [0, 3, 7, 2]
}

purchases = pd.DataFrame(data, index=['June', 'Robert', 'Lily', 'David'])
purchases

        Apples  Oranges
June         3        0
Robert       2        3
Lily         0        7
David        1        2

In [36]:
purchases.loc['June']

Apples     3
Oranges    0
Name: June, dtype: int64

In [38]:
df = pd.read_csv('purchases.csv', index_col=0)
df

        apples  oranges
June         3        0
Robert       2        3
Lily         0        7
David        1        2